default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lembrete_development

test:
  <<: *default
  database: lembrete_test

production:
  <<: *default
  database: lembrete_production
  username: lembrete
  password: <%= ENV['LEMBRETE_DATABASE_PASSWORD'] %>
